const devices = [
  {
    manufacturer: "Apple",
    model: "iPhone 14 Pro",
    cpu: "A16 Bionic",
    type: "iPhone",
    os: "iOS 16",
  },
  {
    manufacturer: "Apple",
    model: "iPhone 13",
    cpu: "A15 Bionic",
    type: "iPhone",
    os: "iOS 15",
  },
  {
    manufacturer: "Apple",
    model: "iPhone SE (2022)",
    cpu: "A15 Bionic",
    type: "iPhone",
    os: "iOS 15",
  },
  {
    manufacturer: "Apple",
    model: "iPad Pro 2021",
    cpu: "M1",
    type: "iPad",
    os: "iPadOS 15",
  },
  {
    manufacturer: "Apple",
    model: 'MacBook Pro 16" 2021',
    cpu: "M1 Pro",
    type: "Laptop",
    os: "macOS Monterey",
  },
  {
    manufacturer: "Apple",
    model: "MacBook Air M2",
    cpu: "M2",
    type: "Laptop",
    os: "macOS Ventura",
  },
  {
    manufacturer: "Samsung",
    model: "Galaxy S21 Ultra",
    cpu: "Exynos 2100",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "Samsung",
    model: "Galaxy Note 20",
    cpu: "Exynos 990",
    type: "Android",
    os: "Android 10",
  },
  {
    manufacturer: "Samsung",
    model: "Galaxy A52",
    cpu: "Qualcomm Snapdragon 720G",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "Samsung",
    model: "Galaxy Tab S7",
    cpu: "Qualcomm Snapdragon 865+",
    type: "Android Tablet",
    os: "Android 10",
  },
  {
    manufacturer: "Samsung",
    model: "Galaxy Z Fold 3",
    cpu: "Qualcomm Snapdragon 888",
    type: "Android Foldable",
    os: "Android 11",
  },
  {
    manufacturer: "Google",
    model: "Pixel 6",
    cpu: "Google Tensor",
    type: "Android",
    os: "Android 12",
  },
  {
    manufacturer: "Google",
    model: "Pixel 5a",
    cpu: "Qualcomm Snapdragon 765G",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "Google",
    model: "Pixel 4a",
    cpu: "Qualcomm Snapdragon 730G",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "Microsoft",
    model: "Surface Laptop 4",
    cpu: "Intel Core i7-1185G7",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Microsoft",
    model: "Surface Book 3",
    cpu: "Intel Core i7-1065G7",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Dell",
    model: "XPS 13",
    cpu: "Intel Core i7-1185G7",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Dell",
    model: "Inspiron 15 7000",
    cpu: "Intel Core i5-1035G1",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "HP",
    model: "Spectre x360 14",
    cpu: "Intel Core i7-1165G7",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "HP",
    model: "Envy 13",
    cpu: "Intel Core i5-1135G7",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Lenovo",
    model: "ThinkPad X1 Carbon",
    cpu: "Intel Core i7-1165G7",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Lenovo",
    model: "Yoga 9i",
    cpu: "Intel Core i7-1185G7",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Asus",
    model: "ROG Strix Scar 15",
    cpu: "AMD Ryzen 9 5900HX",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Asus",
    model: "ZenBook 14",
    cpu: "Intel Core i7-1165G7",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Acer",
    model: "Predator Helios 300",
    cpu: "Intel Core i7-10750H",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Acer",
    model: "Swift 3",
    cpu: "AMD Ryzen 7 4700U",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Sony",
    model: "VAIO SX14",
    cpu: "Intel Core i7-1165G7",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Razer",
    model: "Blade 15 Advanced",
    cpu: "Intel Core i7-10875H",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Huawei",
    model: "MateBook X Pro",
    cpu: "Intel Core i5-10210U",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Huawei",
    model: "MateBook 14",
    cpu: "AMD Ryzen 5 4600U",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Xiaomi",
    model: "Mi 11 Ultra",
    cpu: "Qualcomm Snapdragon 888",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "Xiaomi",
    model: "Redmi Note 11",
    cpu: "Qualcomm Snapdragon 680",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "OnePlus",
    model: "OnePlus 9 Pro",
    cpu: "Qualcomm Snapdragon 888",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "OnePlus",
    model: "OnePlus Nord",
    cpu: "Qualcomm Snapdragon 765G",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "LG",
    model: "Gram 17",
    cpu: "Intel Core i7-1165G7",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "LG",
    model: "V60 ThinQ",
    cpu: "Qualcomm Snapdragon 865",
    type: "Android",
    os: "Android 10",
  },
  {
    manufacturer: "Motorola",
    model: "Moto G Power",
    cpu: "Qualcomm Snapdragon 662",
    type: "Android",
    os: "Android 10",
  },
  {
    manufacturer: "Motorola",
    model: "Moto Edge 2021",
    cpu: "Qualcomm Snapdragon 778G",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "Nokia",
    model: "Nokia 8.3 5G",
    cpu: "Qualcomm Snapdragon 765G",
    type: "Android",
    os: "Android 10",
  },
  {
    manufacturer: "Nokia",
    model: "Nokia 7.2",
    cpu: "Qualcomm Snapdragon 660",
    type: "Android",
    os: "Android 10",
  },
  {
    manufacturer: "Dell",
    model: "G5 15",
    cpu: "Intel Core i7-10750H",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "HP",
    model: "Pavilion 15",
    cpu: "AMD Ryzen 5 5500U",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Lenovo",
    model: "ThinkPad T14",
    cpu: "Intel Core i7-10610U",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Asus",
    model: "TUF Gaming A15",
    cpu: "AMD Ryzen 7 4800H",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Acer",
    model: "Nitro 5",
    cpu: "Intel Core i5-9300H",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Razer",
    model: "Blade Stealth 13",
    cpu: "Intel Core i7-1165G7",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Sony",
    model: "VAIO SX12",
    cpu: "Intel Core i7-1065G7",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Huawei",
    model: "MateBook D 15",
    cpu: "AMD Ryzen 5 3500U",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Xiaomi",
    model: "Mi Mix 4",
    cpu: "Qualcomm Snapdragon 888",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "Google",
    model: "Pixel 6 Pro",
    cpu: "Google Tensor",
    type: "Android",
    os: "Android 12",
  },
  {
    manufacturer: "Google",
    model: "Pixel 5",
    cpu: "Qualcomm Snapdragon 765G",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "Apple",
    model: "iPad Air (2022)",
    cpu: "M1",
    type: "iPad",
    os: "iPadOS 15",
  },
  {
    manufacturer: "Apple",
    model: "iPhone 11",
    cpu: "A13 Bionic",
    type: "iPhone",
    os: "iOS 14",
  },
  {
    manufacturer: "Samsung",
    model: "Galaxy A72",
    cpu: "Qualcomm Snapdragon 720G",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "Samsung",
    model: "Galaxy S20 FE",
    cpu: "Exynos 990",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "Huawei",
    model: "P40 Pro",
    cpu: "Kirin 990",
    type: "Android",
    os: "Android 10",
  },
  {
    manufacturer: "Xiaomi",
    model: "Redmi Note 10 Pro",
    cpu: "Qualcomm Snapdragon 732G",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "Asus",
    model: "ROG Phone 5",
    cpu: "Qualcomm Snapdragon 888",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "Dell",
    model: "XPS 17",
    cpu: "Intel Core i9-11980HK",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "HP",
    model: "Omen 15",
    cpu: "Intel Core i7-10750H",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Lenovo",
    model: "Legion 5 Pro",
    cpu: "AMD Ryzen 7 5800H",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Asus",
    model: "ZenBook Flip 14",
    cpu: "Intel Core i7-1165G7",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Acer",
    model: "Aspire 5",
    cpu: "Intel Core i5-1135G7",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Microsoft",
    model: "Surface Laptop Go",
    cpu: "Intel Core i5-1035G1",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Razer",
    model: "Blade 17",
    cpu: "Intel Core i9-11900H",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Sony",
    model: "VAIO SX14",
    cpu: "Intel Core i7-1065G7",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Huawei",
    model: "MateBook X Pro",
    cpu: "Intel Core i5-10210U",
    type: "Laptop",
    os: "Windows 10",
  },
  {
    manufacturer: "Xiaomi",
    model: "Mi 10T Pro",
    cpu: "Qualcomm Snapdragon 865",
    type: "Android",
    os: "Android 10",
  },
  {
    manufacturer: "OnePlus",
    model: "OnePlus 8T",
    cpu: "Qualcomm Snapdragon 865",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "Nokia",
    model: "Nokia 9 PureView",
    cpu: "Qualcomm Snapdragon 845",
    type: "Android",
    os: "Android 9",
  },
  {
    manufacturer: "Motorola",
    model: "Moto G60",
    cpu: "Qualcomm Snapdragon 732G",
    type: "Android",
    os: "Android 11",
  },
  {
    manufacturer: "LG",
    model: "Wing",
    cpu: "Qualcomm Snapdragon 765G",
    type: "Android",
    os: "Android 10",
  },
  {
    manufacturer: "Google",
    model: "Pixel 4 XL",
    cpu: "Qualcomm Snapdragon 855",
    type: "Android",
    os: "Android 10",
  },
  {
    manufacturer: "Apple",
    model: "iPhone XR",
    cpu: "A12 Bionic",
    type: "iPhone",
    os: "iOS 13",
  },
  {
    manufacturer: "Apple",
    model: "iPhone X",
    cpu: "A11 Bionic",
    type: "iPhone",
    os: "iOS 12",
  },
];
module.exports = devices;
